# General Information
title: Berry House
author: Daniel Schultz
email: admin@berryhousefdl.com
description: > # this means to ignore newlines until "baseurl:"
# Build settings
url: https://github.com/berryhousefdl
baseurl: https://github.com/berryhousefdl/berryhousefdl
permalink: pretty
# SASS directory
sass:
    sass_dir: _sass
# Custom pages directory to keep root directory uncluttered
include: ['_pages']
# Markdown
markdown: kramdown
# GitHub flavored Markdown
input: GFM
# Exclusions
exclude:
  - Gemfile
  - Gemfile.lock
